### ISSUE TITLE
The OHEM question

### ISSUE THREAD

**Issue by manutdzou** [YuwenXiong/py-R-FCN#49]
I read the codes and I'm confused in OHEM, you just put all the proposal rois (total 300 + gt number)into the next step in end2end training. When you sort the roi loss and hard mining the proposal rois examples? Thank you!

**Comment by Oh233** [comment]
In BoxAnnotatorOHEM layer.

**Comment by manutdzou** [comment]
Thank you, I know. It's a different implement compared with doing OHEM in python layer as I do before
