### ISSUE TITLE
Usage of __C.TEST.NMS 

### ISSUE THREAD

**Issue by plopd** [YuwenXiong/py-R-FCN#60]
The comments in `config.py` regarding  `__C.TEST.NMS` seem to contain a typo, namely it states
```
# Overlap threshold used for non-maximum suppression (suppress boxes with
# IoU >= this threshold)
__C.TEST.NMS = 0.3
```
But it should state:

```
# Overlap threshold used for non-maximum suppression (suppress boxes with
# IoU #<=# this threshold)
```
Can you confirm this ?

**Comment by liyi14** [comment]
NMS is designed to suppress boxes which heavily overlap with another box which has a higher score.
