### ISSUE TITLE
Multi-GPU Support

### ISSUE THREAD

**Issue by yehan-xiao** [YuwenXiong/py-R-FCN#76]
Hi, 

I'm a newcomer, arranged to maintain a system using this py-R-FCN. I want to use this system on a machine with multi-GPU.
But I see in the Read-me, it suggests to use mxNet for multi-GPU train/test. 
Now the new version caffe supports multi-GPU, does py-R-FCN run on multi-GPU automatically?

Thanks!

**Comment by liyi14** [comment]
Maybe you can check this repo https://github.com/bharatsingh430/py-R-FCN-multiGPU
