### ISSUE TITLE
Is the alternative-optimization result is trained with OHEM?

### ISSUE THREAD

**Issue by Zehaos** [YuwenXiong/py-R-FCN#81]
Hi, @YuwenXiong 

I saw that the alternative-optimization result is very close to joint training result(and there is only one script [rfcn_alt_opt_5stage_ohem.sh](https://github.com/YuwenXiong/py-R-FCN/blob/master/experiments/scripts/rfcn_alt_opt_5stage_ohem.sh) for alternative-optimization), I wonder that was it trained with OHEM?

https://github.com/YuwenXiong/py-R-FCN#joint-training
https://github.com/YuwenXiong/py-R-FCN#alternative-optimization

**Comment by YuwenXiong** [comment]
Yes, as you can see there is a suffix `ohem` in the end of the script name.

**Comment by Zehaos** [comment]
@YuwenXiong Is there a result without OHEM? Thank you very much.

**Comment by YuwenXiong** [comment]
Unfortunately no, you can train a model by your self or refer the paper's result.
