### ISSUE TITLE
Why the output of "rfcn_bbox" layer is 392?

### ISSUE THREAD

**Issue by panovr** [YuwenXiong/py-R-FCN#83]
In file `train_agnostic.prototxt` [line 3759](https://github.com/YuwenXiong/py-R-FCN/blob/master/models/pascal_voc/ResNet-50/rfcn_end2end/train_agnostic.prototxt#L3759):

```
layer {
    bottom: "conv_new_1"
    top: "rfcn_bbox"
    name: "rfcn_bbox"
    type: "Convolution"
    convolution_param {
        num_output: 392 #8*(7^2) cls_num*(score_maps_size^2)
        kernel_size: 1
        pad: 0
        weight_filler {
            type: "gaussian"
            std: 0.01
        }
        bias_filler {
            type: "constant"
            value: 0
        }
    }
    param {
        lr_mult: 1.0
    }
    param {
        lr_mult: 2.0
    }
}
```
The output number is 392. The comment says that 392 equals `cls_num*(score_map_size^2)`. However,
why `cls_num` is 8? I think this should be `2*4*(score_map_size^2)`.

**Comment by liyi14** [comment]
You are right. We forget to fix this comments.
